# curl -u "sk_live_xxx:" "https://api.octopus.energy/v1/products/AGILE-FLEX-22-11-25/electricity-tariffs/E-1R-AGILE-FLEX-22-11-25-E/standard-unit-rates/"
# $env:OCTOPUS_API_KEY = "sk_live_"

@apiKey={{$processEnv OCTOPUS_API_KEY}}
@url=https://api.octopus.energy/v1
@accountId=A-34298F7D

###
GET {{url}}/accounts/A-34298F7D
Authorization: Basic {{apiKey}}:

###
GET {{url}}/products/VAR-22-11-01/electricity-tariffs/E-1R-VAR-22-11-01-E/standard-unit-rates/?page=1
Authorization: Basic {{apiKey}}:

###
GET {{url}}/products/AGILE-FLEX-22-11-25/electricity-tariffs/E-1R-AGILE-FLEX-22-11-25-E/standard-unit-rates/?page=1
Authorization: Basic {{apiKey}}:

###
https://api.octopus.energy/v1/products